### ISSUE TITLE
Error if other plugin has the same command names

### ISSUE THREAD

**Issue by Frogperson** [TheDoffman/EssentialsPro#1]
If another plugin has already loaded that uses the same command names as EssentialsPro, like spawn, setspawn, home, etc. it throws an error in the console and fails to load. This is a Paper server running build 42. The same error is present on Spigot as well, but for some reason the plugin stays enabled.

```
[16:17:58 INFO]: [HomeSpawn] Enabling HomeSpawn v3.1.2
[16:17:58 INFO]: [HomeSpawn] HomeSpawn v3.1.2 has been enabled
[16:17:58 INFO]: [EssentialsPro] Enabling EssentialsPro v1.6*
[16:17:58 ERROR]: Error occurred while enabling EssentialsPro v1.6 (Is it up to date?)
java.lang.NullPointerException: null
        at me.thedoffman.essentialspro.commands.SetSpawn.<init>(SetSpawn.java:18) ~[?:?]
        at me.thedoffman.essentialspro.main.Main.onEnable(Main.java:92) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.1.jar:git-Paper-42]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.1.jar:git-Paper-42]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:419) ~[patched_1.14.1.jar:git-Paper-42]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:464) ~[patched_1.14.1.jar:git-Paper-42]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:378) ~[patched_1.14.1.jar:git-Paper-42]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:464) ~[patched_1.14.1.jar:git-Paper-42]
        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:280) ~[patched_1.14.1.jar:git-Paper-42]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:855) ~[patched_1.14.1.jar:git-Paper-42]
        at java.lang.Thread.run(Unknown Source) [?:?]
[16:17:58 INFO]: [EssentialsPro] Disabling EssentialsPro v1.6
```

**Comment by TheDoffman** [comment]
Hey! Thanks for reaching out.

It seems like the plugin is allowing the other one to take control of that command.
Is there a reason you need to have 2 plugins with the cam ands you mentioned. I will have to implement something to not allow commands to be taken over if this is an on going issue.

If you have any other issues or info about your issue please post here.

Thanks,
TheDoffman

**Comment by Frogperson** [comment]
The reason for the second plugin (HomeSpawn), was to allow players to set more than one home. So I actually want other plugins to take control of your /sethome and /home commands. I just don't want your plugin to crash when they do :)

The error is still in the console even on Spigot, the only difference is the plugin doesn't get disabled. If you fix the error, then your plugin should hopefully work perfectly fine on Paper.

**Comment by TheDoffman** [comment]
Thanks for the input! Not sure if you know but EssentialsPro was designed to be able to allow more than one home. I will Look into this issue tonight and reply with a fix.

Thanks again!

**Comment by Frogperson** [comment]
> Not sure if you know but EssentialsPro was designed to be able to allow more than one home per player.

I actually was not aware of that, thank you. Is the command simply `/sethome homeName`? And is the amount configurable anywhere to allow for a maximum? I wouldn't want players having infinite homes. I didn't see anything in the config file, nor any permissions for it other than just allowing the /home command altogether. 

Also since players have already set up their homes with HomeSpawn,  I can't really easily switch to using EssentialPro's homes now.

**Comment by TheDoffman** [comment]
Well yes you can set up multiple homes just by typing /sethome <name>. The permission nodes for limiting the amount of homes is being implemented tonight actually with an update!

Thanks,
TheDoffman
